use blackchip;


/* Query 1*/
/*Time has come for the HR Manager of BlackChip semiconductors to
 roll-out the annual bonus for every employee. He has decided to set around 
 3% on overall profit generated by the projects worked by the employee as a bonus. */
 
SELECT * FROM
(
SELECT tab3.employee_id,e.EMPLOYEE_FIRST_NAME,e.EMPLOYEE_LAST_NAME, e.Department_name, COUNT(*) AS "Number of projects",  concat('$',SUM((s.Profit_percentage*tab3.budget)/100)) AS "Net profit", concat('$',(SUM((s.Profit_percentage*tab3.budget)/100)*0.03)) AS Annual_bonus FROM
(
SELECT o.order_id,  d.employee_id, o.budget  FROM orders o INNER JOIN design d ON o.order_id=d.order_id
UNION all
SELECT o.order_id, l.employee_id, o.budget FROM orders o INNER JOIN layout l ON o.order_id=l.order_id
UNION all
SELECT o.order_id, v.employee_id, o.budget FROM orders o INNER JOIN  verIFicatiON v ON o.order_id=v.order_id
UNION all
SELECT o.order_id, s.employee_id, o.budget FROM orders o INNER JOIN sales s ON o.order_id = s.order_id) AS tab3 
JOIN
sales s ON s.order_id=tab3.order_id 
JOIN
employees e ON tab3.employee_id=e.employee_id
GROUP BY tab3.employee_id ORDER BY Annual_Bonus DESC ) AS tab33;



/* Query 2 */
/* Blackchip semiconductors company wants to track their hardware designs,
 specifications, design cycle time, bugs resolving time as well as layout
 specifications in order to optimize their time and scope.
 */


SELECT d.design_id,DATEDIFF(d.dend_date,d.dstart_date) AS 'design_duratiON (days)',
features,DATEDIFF(v.Bugs_logged_out_date,v.Bugs_logged_in_date) AS 'bug_resolving_duratiON (days)',
v.bugs_DESCriptiON,l.layout_plan_DESCriptiON,l.metal_layer,l.voltage_domain FROM design d 
JOIN layout l ON d.design_id=l.design_id
JOIN verIFicatiON v ON l.design_id=v.design_id;




/* Query 3 */
/* The sales team of Blackchip semiconductors company is
 given a task of finding high profitable clients among the existing ones. 
 */

SELECT client_id,
if(client_id='C1','Dell',if(client_id='C2','Toshibha',if(client_id='C3','Seagate','Western Digital'))) as client_name,
no_of_locations,
no_of_orders,SUM_of_order_size,
Clients_total_budget,profit
FROM (
SELECT o.client_id,COUNT(o.location_id) AS no_of_locations, 
COUNT(o.order_id) AS no_of_orders,
SUM(o.order_size) AS SUM_of_order_size,
concat('$',round(SUM(o.budget),2)) AS "Clients_total_budget",
concat('$',round(SUM((s.budget*s.profit_percentage)/100),2)) AS profit 
FROM sales s
JOIN orders o ON s.order_id=o.order_id 
GROUP BY o.client_id
ORDER BY profit DESC) AS t2;




/* Query 4.1 */
/*The HR manager of Blackchip semiconductors wants to keep track of resources
 and their salary allocation across the several verticals of the company to
 make more informed decisions when hiring and allocating new resources to a team.*/

SELECT  department_name,COUNT(employee_id), 
SUM(hrs_worked_per_day*20*hourly_rate),
 MAX(hrs_worked_per_day*20*hourly_rate), 
 MIN(hrs_worked_per_day*20*hourly_rate), 
 AVG(hrs_worked_per_day*20*hourly_rate) 
 FROM employees GROUP BY department_name;
 
 /* Query 4.2*/
 SELECT department_name,IF(department_name='Design',COUNT(employee_id),
 IF(department_name='VerIF',COUNT(employee_id),
 IF(department_name='Layout',COUNT(employee_id),
 IF(department_name='Sales',COUNT(employee_id),0)))) AS Total_no_employees,
 
 IF(department_name='Design',SUM(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='VerIF',SUM(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Layout',SUM(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Sales',SUM(hrs_worked_per_day*20*hourly_rate),0)))) AS Total_Salary,
 
 IF(department_name='Design',AVG(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='VerIF',AVG(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Layout',AVG(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Sales',AVG(hrs_worked_per_day*20*hourly_rate),0)))) AS AVG_Salary,
 
 IF(department_name='Design',MAX(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='VerIF',MAX(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Layout',MAX(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Sales',MAX(hrs_worked_per_day*20*hourly_rate),0)))) AS MAX_Salary,
 
 IF(department_name='Design',MIN(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='VerIF',MIN(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Layout',MIN(hrs_worked_per_day*20*hourly_rate),
 IF(department_name='Sales',MIN(hrs_worked_per_day*20*hourly_rate),0)))) AS MIN_salary
 
 FROM employees GROUP BY department_name;
 
/* Query 5*/
/*During the pandemic, the sales and profits have gone drastically down, 
the sales team of Blackchip semiconductors company is given a task of
 finding high profitable locations among the existing ones to prioritize and plan their future investments.*/

SELECT 
l.location_id, l.location_name, COUNT(o.client_id) as no_of_clients, SUM(o.order_size) as total_orders,  
concat('$',round(SUM((s.budget*s.profit_percentage)/100),2)) AS profit,
concat('$',round((SUM((s.budget*s.profit_percentage)/100))/COUNT(o.client_id),2)) AS Normalized_profit_per_client  ,
IF(round((SUM((s.budget*s.profit_percentage)/100))/COUNT(o.client_id),2)  < 100000,
'Low', IF(round((SUM((s.budget*s.profit_percentage)/100))/COUNT(o.client_id),2)  > 500000 ,
'High', 'Medium')) AS category
FROM locations l 
JOIN orders o ON l.location_id=o.location_id 
JOIN sales s ON s.order_id=o.order_id GROUP BY l.location_id ORDER BY normalized_profit_per_client DESC;